# Generated by Django 2.2.5 on 2019-10-08 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sm_auth', '0002_tempregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('dt', models.DateTimeField()),
                ('status', models.CharField(choices=[('A', '已接单'), ('S', '已完成'), ('C', '已取消')], max_length=1)),
                ('recv_method', models.BooleanField()),
                ('recv_info', models.TextField()),
                ('goods', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm_auth.User')),
            ],
        ),
    ]
