# Generated by Django 2.2.5 on 2019-10-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='id',
        ),
        migrations.AlterField(
            model_name='config',
            name='key',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
