# Generated by Django 2.2.5 on 2019-09-28 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.IntegerField()),
                ('image', models.CharField(max_length=54)),
                ('description', models.TextField()),
                ('statistics', models.TextField()),
                ('tag', models.ManyToManyField(to='sm_shop.Tags')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm_shop.Types')),
            ],
        ),
    ]
