# Generated by Django 2.2.5 on 2019-10-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=18)),
                ('nick', models.CharField(max_length=30)),
                ('avator', models.CharField(max_length=11)),
                ('recv_infos', models.TextField()),
                ('psn_gender', models.BooleanField(blank=True)),
                ('psn_birthday', models.DateTimeField(blank=True)),
                ('psn_favor', models.CharField(blank=True, choices=[('N', '无')], max_length=1)),
                ('goods', models.TextField()),
                ('reg_date', models.DateTimeField()),
                ('used_time', models.TextField()),
                ('tab_click_num', models.IntegerField()),
                ('consumption', models.DecimalField(decimal_places=2, max_digits=16)),
                ('order_num', models.IntegerField()),
                ('bad_order_num', models.IntegerField()),
            ],
        ),
    ]
