# Generated by Django 2.2.5 on 2019-10-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempRegister',
            fields=[
                ('phone', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('check_code', models.CharField(max_length=4)),
            ],
        ),
    ]
